### PR TITLE
add new SEO tool

### PR DESCRIPTION
**Pull request by goenning**

### CODE REVIEW

**Comment by hilmanski** [comment]
Thanks @goenning !

**Comment by hilmanski** [comment]
Currently it's located under "rank tracking", do you think we should put this on a different category?

**Comment by goenning** [comment]
I couldn’t find a better one, maybe we could create an “Analytics” category?

**Comment by hilmanski** [comment]
Sure, good idea, I'll put it alongside Google's console. Thanks!

**Comment by hilmanski** [comment]
*no action needed from your side.

**Pull request merged**
